/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;

public class App {
    public static void main(String[] args) {
        Options options = new Options();
        options.addOption("b", true, "batch file containing expressions to evaluate");
        options.addOption("h", false, "print usage message");
        options.addOption("o", true, "output file");
        options.addOption("batch", true, "batch file containing expressions to evaluate");
        options.addOption("help", false, "print usage message");
        options.addOption("output", true, "output file");

        CommandLineParser parser = new DefaultParser();
        CommandLine cmd = null;
        try {
            cmd = parser.parse(options, args);

            if (cmd.hasOption('b') || cmd.hasOption("batch")) {
                if (cmd.getOptionValue('b') != null) {
                    System.out.println("Batch value: " + cmd.getOptionValue('b'));
                }
                else {
                    System.out.println("Batch value: " + cmd.getOptionValue("batch"));
                }
            }
            else if (cmd.hasOption('h') || cmd.hasOption("help")) {
                System.out.println("");
            }
            else if (cmd.hasOption('o') || cmd.hasOption("output")) {
                if (cmd.getOptionValue('o') != null) {
                    System.out.println("Batch value: " + cmd.getOptionValue('o'));
                }
                else {
                    System.out.println("Output value: " + cmd.getOptionValue("output"));
                }
            }
        }
        catch (Exception error){
            System.out.println("ERROR: " + error);
        }
    }
}
